### ISSUE TITLE
Consider exposing IntoTimes trait as part of the public API

### ISSUE THREAD

**Issue by cppforliving** [ggriffiniii/httptest#14]
Currently [ExpectationBuilder::times](https://docs.rs/httptest/0.15.2/httptest/struct.ExpectationBuilder.html#method.times)  method has an argument which is bounded by a private `IntoTimes` trait, consider exposing this trait in public API, the use case might be an attempt to wrap the expectation code into a function with generic `times` argument

```rust
fn wrapper(times: impl IntoTimes) {
    Expectation::matching(request::method("POST"))
        .times(times)
        .respond_with(status_code(204))
}
```

**Comment by ggriffiniii** [comment]
Good idea. This is done and I've pushed it in v0.15.3

**Comment by cppforliving** [comment]
Thank you!
