### ISSUE TITLE
Option to disable IPv6 support or prefer IPv4

### ISSUE THREAD

**Issue by tjkirch** [ggriffiniii/httptest#16]
Unfortunately some CI setups don't work with IPv6 (GitHub still isn't perfect) and currently require locking to httptest 0.15.2.  It'd be nice to have a cargo feature flag for IPv6, perhaps, or just a constructor option for disabling IPv6 or preferring IPv4.

**Comment by ggriffiniii** [comment]
This should be possible today using the [ServerBuilder::bind_addr](https://docs.rs/httptest/0.15.3/httptest/struct.ServerBuilder.html#method.bind_addr) method. Starting the server listening on ipv4 loopback would look something like:

```rust
ServerBuilder::new().bind_addr(([127, 0, 0, 1], 0).into()).run().unwrap()
```

**Comment by tjkirch** [comment]
Thanks!  Also using `Server.addr()` instead of `localhost:port` helps.  :smile:  :crab:
