### ISSUE TITLE
httptest requires undeclared tokio feature `macros`

### ISSUE THREAD

**Issue by neoeinstein** [ggriffiniii/httptest#24]
When pulled in as a dependency, `httptest` relies on `tokio::select!`, which requires the `macros` feature from tokio. This is a problem for intermediate libraries that may not themselves require enabling the `macros` feature.

Should just need to update `Cargo.toml` to include the `macro` feature in `dependencies`. This is not apparent here because you pull in `macro` in `dev-dependencies`, which gets unified when run locally.

**Comment by ggriffiniii** [comment]
Thanks for the report. The tokio::select usage was recently introduced by #22. I'll update the Cargo.toml and push out a fix.
