### ISSUE TITLE
Re-export some types?

### ISSUE THREAD

**Issue by djmitche** [ggriffiniii/httptest#9]
The `Matcher` and `Responder`s trait refer to external types from the `http`, `hyper` and `bytes` crate.  It would be great if `httptest` re-exported those types to avoid having to add them to my project's `Cargo.toml`, and so that my tests can automatically use the same version of those crates that httptest does.

I'm not totally clear on the typical Rust way to do this -- if my suggestion is incorrect, pointers to best practice would be great.

**Comment by ggriffiniii** [comment]
Thanks for the issue report. Re-exporting the types sounds reasonable to me. I was hoping that the http crate would reach 1.0 relatively soon, but it doesn't seem imminent. In the meantime re-exporting the types will make it easier for users. I'll try to get to that soon, but it might take a few days before I have the time.

**Comment by djmitche** [comment]
No rush :)

**Comment by ggriffiniii** [comment]
I re-exported `http` and `bytes` at the root of httptest as of v0.15.1. Feel free to reopen if it looks like there are other types that should be re-exported.

**Comment by djmitche** [comment]
Beautiful, thanks!
